[
    {
        "Name":"Somu",
        "Payment":{
            "Total":600
        },
        "Transaction":{
            "Price":400
        }
    },
    {
        "Name":"Arthur",
        "Payment":{
            "Total":500
        },
        "Transaction":{
            "Price":350
        }
    },
    {
        "Name":"Charles",
        "Payment":{
            "Total":550
        },
        "Transaction":{
            "Price":450
        }
    },
    {
        "Name":"John",
        "Payment":{
            "Total":600
        },
        "Transaction":{
            "Price":600
        }
    },
    {
        "Name":"Lenny",
        "Payment":{
            "Total":600
        },
        "Transaction":{
            "Price":150
        }
    }
]